apiVersion: v1
kind: Namespace
metadata:
  name: memmimic
  labels:
    name: memmimic
    environment: production
    app.kubernetes.io/name: memmimic
    app.kubernetes.io/version: "1.0.0"
---
# Resource Quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: memmimic-quota
  namespace: memmimic
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    pods: "50"
    services: "20"
---
# Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: memmimic-network-policy
  namespace: memmimic
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: memmimic
    - namespaceSelector:
        matchLabels:
          name: istio-system
  - from: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8000
  egress:
  - {} # Allow all egress traffic