# Optimized Tales System Configuration
# This configuration enables high-performance tale management with 10-100x performance improvements

tale_system:
  # Primary backend selection
  use_optimized_backend: true
  
  # Performance monitoring and adaptive switching
  enable_performance_monitoring: true
  enable_gradual_migration: true
  migration_threshold_ms: 100.0  # Switch to optimized if legacy > 100ms
  
  # Optimized system settings
  cache_size: 1000
  enable_compression: true
  enable_search_index: true
  
  # File paths
  legacy_tales_path: "tales"
  optimized_db_path: "tales_optimized.db"
  performance_log_path: "tale_performance.log"

# Performance targets
performance:
  target_response_time_ms: 5.0     # Sub-5ms response time target
  cache_hit_rate_target: 0.85      # 85% cache hit rate target
  compression_ratio_target: 0.7    # 30% compression savings target

# Migration settings
migration:
  auto_migrate_on_startup: false   # Set to true for automatic migration
  backup_legacy_system: true       # Keep legacy system as backup
  migration_batch_size: 100        # Process migrations in batches

# Monitoring
monitoring:
  log_performance_metrics: true
  performance_alert_threshold: 2.0  # Alert if performance degrades 2x
  health_check_interval_seconds: 300  # Check system health every 5 minutes